name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Build
        run: devbox run -q build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/cft-linux
            dist/cft-linux-baseline
            dist/cft-macos
            dist/cft-macos-arm64
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
